/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./index.html",
    "node_modules/flowbite-react/dist/esm/**/*.mjs",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffd9e4",
        "secondary-fixed-dim": "#ffb0cd",
        "on-primary": "#3c2f00",
        "on-tertiary": "#480081",
        tertiary: "#e1c2ff",
        "surface-container-high": "#2a2a2a",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed": "#2c0051",
        "inverse-primary": "#735c00",
        "tertiary-container": "#ce9eff",
        background: "#131313",
        "outline-variant": "#4d4635",
        "surface-container-low": "#1c1b1b",
        secondary: "#ffb0cd",
        "on-tertiary-container": "#6500b1",
        "on-background": "#e5e2e1",
        "on-surface-variant": "#d0c5af",
        "on-secondary-fixed-variant": "#8c0053",
        "primary-container": "#d4af37",
        "on-secondary-container": "#ffe6ed",
        "inverse-on-surface": "#313030",
        "surface-container": "#201f1f",
        "on-primary-container": "#554300",
        "secondary-container": "#cd037c",
        "surface-bright": "#393939",
        "primary-fixed-dim": "#e9c349",
        "surface-tint": "#e9c349",
        outline: "#99907c",
        surface: "#131313",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "on-error": "#690005",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#dcb8ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#3e0022",
        "surface-container-highest": "#353534",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#efdbff",
        "on-secondary": "#640039",
        primary: "#f2ca50",
        "on-tertiary-fixed-variant": "#6700b5",
        "surface-dim": "#131313",
        error: "#ffb4ab",
        "primary-fixed": "#ffe088",
        dark: {
          900: "#1A1A1A",
          800: "#2B2B2B",
          700: "#333333",
          600: "#404040",
        },
        accent: {
          DEFAULT: "#9F7AEA",
          light: "#B794F4",
          dark: "#805AD5",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-x": "32px",
        gutter: "24px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-md": "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        hanken: ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.3", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
      },
    },
  },
  // eslint-disable-next-line no-undef
  plugins: [require("flowbite/plugin"), require("tailwindcss-animated")],
};
